name: Feature request
description: Provide context for the feature you are requesting
labels: ["enhancement"]
assignees:
  - smatar22
  - RustyCPR
body:
  - type: textarea
    attributes:
      label: Describe the the feature you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other notes
      description: Add anything else you thing is important.